// <auto-generated />
using APICaching.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APICaching.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240906080454_SeedTodoTable")]
    partial class SeedTodoTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APICaching.Models.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Completed")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:JsonPropertyName", "completed");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "title");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "userId");

                    b.HasKey("Id");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Completed = true,
                            Title = "Buy groceries",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Completed = false,
                            Title = "Call Mom",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Completed = true,
                            Title = "Finish project report",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Completed = false,
                            Title = "Book doctor appointment",
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            Completed = true,
                            Title = "Clean the house",
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            Completed = false,
                            Title = "Fix the leaky faucet",
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            Completed = true,
                            Title = "Read a book",
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            Completed = false,
                            Title = "Exercise for 30 minutes",
                            UserId = 2
                        },
                        new
                        {
                            Id = 9,
                            Completed = true,
                            Title = "Prepare dinner",
                            UserId = 2
                        },
                        new
                        {
                            Id = 10,
                            Completed = false,
                            Title = "Reply to emails",
                            UserId = 2
                        },
                        new
                        {
                            Id = 11,
                            Completed = true,
                            Title = "Submit tax forms",
                            UserId = 3
                        },
                        new
                        {
                            Id = 12,
                            Completed = false,
                            Title = "Pay utility bills",
                            UserId = 3
                        },
                        new
                        {
                            Id = 13,
                            Completed = true,
                            Title = "Plan vacation trip",
                            UserId = 3
                        },
                        new
                        {
                            Id = 14,
                            Completed = false,
                            Title = "Buy a gift",
                            UserId = 3
                        },
                        new
                        {
                            Id = 15,
                            Completed = true,
                            Title = "Schedule car maintenance",
                            UserId = 3
                        },
                        new
                        {
                            Id = 16,
                            Completed = false,
                            Title = "Update resume",
                            UserId = 4
                        },
                        new
                        {
                            Id = 17,
                            Completed = true,
                            Title = "Organize files",
                            UserId = 4
                        },
                        new
                        {
                            Id = 18,
                            Completed = false,
                            Title = "Practice a hobby",
                            UserId = 4
                        },
                        new
                        {
                            Id = 19,
                            Completed = true,
                            Title = "Learn a new skill",
                            UserId = 4
                        },
                        new
                        {
                            Id = 20,
                            Completed = false,
                            Title = "Visit a museum",
                            UserId = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
